Feature/uh2011 favorite products
G6-Pegasus/WEB-FE-HTML-CSS-PRJ2 pull request #13
Opened 2024-09-21 06:54 UTC by Katkat04

Finish the section featured products, here are some photos of my work 
![image](https://github.com/user-attachments/assets/1b774d29-6d2e-4b4c-a61f-03a87a68c3b7)
![image](https://github.com/user-attachments/assets/d7e1eb62-fb41-4396-a01a-f2a3b697eb62)
![image](https://github.com/user-attachments/assets/cc4ef5c3-3575-4696-a46a-71b24610758c)
![image](https://github.com/user-attachments/assets/e83b5c96-a4da-4d40-abcc-9fc674429c6f)

2024-09-21 14:34 UTC, Edimar-star requested changes

2024-09-21 14:34 UTC, Edimar-star commented on src/components/home/FeaturedProduct.tsx
it is perfect what you did, but check the requirement in the technical notes of your story, a featured product must be a component in react but not all featured products.

2024-09-22 04:10 UTC, RDCelin approved these changes
Good job

2024-09-22 04:33 UTC, Edimar-star approved these changes

2024-09-22 14:55 UTC, jesusdlacrz approved these changes
bugs fixed, good job.

2024-09-22 15:04 UTC, merged